resolver: lts-13.29

packages:
- .

extra-deps:
- github: KingoftheHomeless/polysemy
  commit: bc49d919d8d67574271fbaf8fbab0c91116d11e4
- polysemy-plugin-0.2.2.0
- type-errors-0.2.0.0
- type-errors-pretty-0.0.0.0
- th-abstraction-0.3.1.0
- bifunctors-5.5.4
- first-class-families-0.5.0.0
- unagi-chan-0.4.1.0

